"""added and configured otps

Revision ID: 9b691c5b7b2d
Revises: d295a8b38bff
Create Date: 2026-09-23 23:05:04.242960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b691c5b7b2d'
down_revision: Union[str, Sequence[str], None] = 'd295a8b38bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_attempts')
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'otp_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('otp_attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
